/*
  The guide module renders local mock profiles and saves only demo hire requests
  in localStorage. It does not submit data or claim a real booking occurred.
*/
const GUIDE_URL="data/guides.json", GUIDE_REQUESTS="exploreCTG_guideRequests";
/* Escapes data before it is placed in a template string. */
function guideSafe(value){const node=document.createElement("div");node.textContent=String(value);return node.innerHTML;}
/* Reads requests defensively so a damaged value cannot break the guide page. */
function guideRequests(){try{const value=JSON.parse(localStorage.getItem(GUIDE_REQUESTS)||"[]");return Array.isArray(value)?value:[]}catch{return [];}}
/* Stores a clearly labelled demo request and returns an explanatory result message. */
function requestGuide(guide){const session=ExploreCTG.getSession();const requests=guideRequests();requests.push({id:"request_"+Date.now(),guideId:guide.id,guideName:guide.name,traveler:session?session.name:"Guest visitor",status:"Demo request only",createdAt:new Date().toISOString()});localStorage.setItem(GUIDE_REQUESTS,JSON.stringify(requests));return session?"Demo request saved in this browser. No real booking or contact was made.":"Demo request saved locally. Log in to see it in your dashboard; no real booking was made.";}
/* Creates a reusable guide card using fields actually present in guides.json. */
function guideCard(guide){return '<article class="destination-card"><img src="'+guideSafe(guide.photo)+'" alt="Profile placeholder for '+guideSafe(guide.name)+'"><div class="destination-card-body"><p class="card-label">'+guideSafe(guide.location)+' · ★ '+guideSafe(guide.rating)+'</p><h2>'+guideSafe(guide.name)+'</h2><p>'+guideSafe(guide.experienceYears)+' years experience · '+guideSafe(guide.languages.join(", "))+'</p><p><strong>Specialties:</strong> '+guideSafe(guide.specialties.join(", "))+'</p><p><strong>Rate:</strong> ৳'+guideSafe(guide.dailyRate)+'/day · '+guideSafe(guide.availability)+'</p><div class="card-meta"><a class="text-link" href="guide-profile.html?id='+encodeURIComponent(guide.id)+'">View Profile →</a><button class="filter-button" data-hire="'+guideSafe(guide.id)+'">Hire Guide</button></div></div></article>';}
/* Binds dynamic hire buttons after cards are inserted into the page. */
function bindHire(guides){document.querySelectorAll("[data-hire]").forEach((button)=>button.addEventListener("click",()=>{const guide=guides.find((item)=>item.id===button.dataset.hire);const note=document.getElementById("guide-message");if(guide&&note){note.textContent=requestGuide(guide);note.className="form-message is-success";}}));}
/* Renders either the listing page or a guide-profile view based on the existing page root. */
function renderGuides(guides){const grid=document.getElementById("guide-grid");if(grid){document.getElementById("guide-status").textContent=guides.length+" local guide profiles available.";grid.innerHTML=guides.map(guideCard).join("");bindHire(guides);return;}const root=document.getElementById("guide-profile-root");if(root){const id=new URLSearchParams(location.search).get("id"),guide=guides.find((item)=>item.id===id);if(!guide){root.innerHTML='<section class="section"><div class="container empty-state"><h1>Guide not found</h1><a class="button button-primary" href="guides.html">Browse guides</a></div></section>';return;}root.innerHTML='<section class="section"><div class="container detail-layout"><article class="detail-story"><a class="back-link" href="guides.html">← Back to Guides</a><img src="'+guideSafe(guide.photo)+'" alt="Profile placeholder for '+guideSafe(guide.name)+'"><h1>'+guideSafe(guide.name)+'</h1><p>'+guideSafe(guide.bio)+'</p><h2>About this guide</h2><p>Based in '+guideSafe(guide.location)+', with '+guideSafe(guide.experienceYears)+' years of experience. Languages: '+guideSafe(guide.languages.join(", "))+'.</p><h2>Specializations</h2><p>'+guideSafe(guide.specialties.join(" · "))+'</p></article><aside class="detail-side"><section class="info-panel"><h2>Guide details</h2><ul class="info-list"><li><strong>Daily demo rate</strong><span>৳'+guideSafe(guide.dailyRate)+'</span></li><li><strong>Availability</strong><span>'+guideSafe(guide.availability)+'</span></li><li><strong>Rating</strong><span>★ '+guideSafe(guide.rating)+' from '+guideSafe(guide.reviewCount)+' reviews</span></li></ul></section><button class="button button-primary detail-action" id="profile-hire">Hire Guide (Demo)</button><p class="form-message" id="guide-message" aria-live="polite"></p></aside></div></section>';document.getElementById("profile-hire").addEventListener("click",()=>{const note=document.getElementById("guide-message");note.textContent=requestGuide(guide);note.className="form-message is-success";});}}
/* Fetches the bundled guide data and communicates local-server errors clearly. */
async function loadGuides(){try{const response=await fetch(GUIDE_URL);if(!response.ok)throw Error();renderGuides(await response.json());}catch{const target=document.getElementById("guide-status")||document.getElementById("guide-profile-root");target.textContent="Guide data could not load. Run this project with Live Server.";}}
document.addEventListener("DOMContentLoaded",loadGuides);
