/*
  Itinerary logic uses structured arrays: each trip contains its metadata and
  activities, all saved under one localStorage key for the dashboard to reuse.
*/
const TRIP_KEY="exploreCTG_itineraries";
/* Gives each inserted activity a unique DOM name without relying on a backend id. */
function activityRow(){const id="activity_"+Date.now()+"_"+Math.random().toString(36).slice(2,6);return '<div class="form-row" data-activity><div><label>Day <input name="'+id+'_day" type="number" min="1" value="1"></label><label>Time <input name="'+id+'_time" type="time"></label></div><div><label>Activity / place <input name="'+id+'_place" placeholder="Visit Patenga Sea Beach"></label><label>Notes <input name="'+id+'_notes" placeholder="Optional details"></label></div><button class="filter-button" type="button" data-remove>Remove</button></div>';}
/* Adds a row and binds its own remove action, keeping activity editing simple. */
function addActivity(){const list=document.getElementById("activity-list");list.insertAdjacentHTML("beforeend",activityRow());list.lastElementChild.querySelector("[data-remove]").addEventListener("click",(event)=>event.currentTarget.closest("[data-activity]").remove());}
/* Reads browser trip storage safely. */
function trips(){try{const value=JSON.parse(localStorage.getItem(TRIP_KEY)||"[]");return Array.isArray(value)?value:[]}catch{return [];}}
/* Rebuilds visible saved trips after saves or deletes. */
function renderTrips(){const root=document.getElementById("saved-trips"),values=trips();root.innerHTML=values.length?values.map((trip)=>'<article class="destination-card"><div class="destination-card-body"><p class="card-label">'+trip.destination+'</p><h2>'+trip.name+'</h2><p>'+trip.startDate+' to '+trip.endDate+'</p><p>'+trip.activities.length+' saved activities</p><button class="filter-button" data-delete="'+trip.id+'">Delete trip</button></div></article>').join(""):'<p class="empty-state">No saved trips yet. Create your first plan above.</p>';root.querySelectorAll("[data-delete]").forEach((button)=>button.addEventListener("click",()=>{localStorage.setItem(TRIP_KEY,JSON.stringify(trips().filter((trip)=>trip.id!==button.dataset.delete)));renderTrips();}));}
/* Validates trip dates and converts activity inputs into readable activity objects. */
function saveTrip(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),note=document.getElementById("trip-message"),name=String(data.get("name")||"").trim(),destination=String(data.get("destination")||"").trim(),startDate=String(data.get("startDate")||""),endDate=String(data.get("endDate")||"");if(!name||!destination||!startDate||!endDate||endDate<startDate){note.textContent="Enter a name, destination and valid date range.";return;}const activities=[...document.querySelectorAll("[data-activity]")].map((row)=>{const fields=row.querySelectorAll("input");return{day:fields[0].value,time:fields[1].value,place:fields[2].value.trim(),notes:fields[3].value.trim()};}).filter((item)=>item.place);const trip={id:"trip_"+Date.now(),name,destination,startDate,endDate,notes:String(data.get("notes")||"").trim(),activities,createdAt:new Date().toISOString()};const values=trips();values.push(trip);localStorage.setItem(TRIP_KEY,JSON.stringify(values));note.textContent="Trip saved in this browser.";note.className="form-message is-success";clearTrip();renderTrips();}
/* Clears editable inputs and restores one helpful starter activity row. */
function clearTrip(){document.getElementById("trip-form").reset();document.getElementById("activity-list").innerHTML="";addActivity();}
/* Start with an activity row and then connect all form actions. */
document.addEventListener("DOMContentLoaded",()=>{addActivity();document.getElementById("add-activity").addEventListener("click",addActivity);document.getElementById("clear-trip").addEventListener("click",clearTrip);document.getElementById("trip-form").addEventListener("submit",saveTrip);renderTrips();});
